name: Run DesigniteJava Analysis on External Repository

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * *' # At 08:00 AM every day

jobs:
  designite_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout external repository
      uses: actions/checkout@v2
      with:
        repository: 'indra-deepika/SE_Bonus_Test_Repo'
        fetch-depth: 0 # Ensures the whole repository is checked out

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # # Assuming DesigniteJava.jar needs to be downloaded or is not in the external repository
    - name: Download DesigniteJava.jar
      run: wget -O DesigniteJava.jar https://raw.githubusercontent.com/indra-deepika/AutomaticRefactoring/master/DesigniteJava.jar

    
    - name: Run DesigniteJava
      run: java -jar DesigniteJava.jar -i ./books-core/src/main/java/com/sismics/books/core/util/mime -o ./DesigniteJavaOutput

    # Optional: Upload DesigniteJava results as an artifact
    - uses: actions/upload-artifact@v2
      with:
        name: designite-results
        path: ./DesigniteJavaOutput/

  process_results:
    permissions:
      contents: write
      pull-requests: write


    needs: designite_analysis
    runs-on: ubuntu-latest
    name: Download Designite Results and Process with Python
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        # Download the artifact from the previous job
        - name: Download DesigniteJava Results
          uses: actions/download-artifact@v2
          with:
            name: designite-results
            path: ./DesigniteJavaOutput

        - name: Install Python dependencies
          run: pip install PyGithub openai

        - name: Process Results with Python
          run: python detectDesignSmells.py ./DesigniteJavaOutput > design_smells_output.txt

        - name: List DesigniteJava Output
          run: ls -l ./DesigniteJavaOutput

        - name: Find Specific Design Smell File
          run: |
            find ./DesigniteJavaOutput -name '*designCodeSmell*' -exec echo "Found design smell file: {}" \;

        - name: Upload Output as Artifact
          uses: actions/upload-artifact@v2
          with:
            name: design-smells-output
            path: design_smells_output.txt



        - name: Run Create Pull Request Script
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
            MY_PAT: ${{ secrets.MY_PAT}}
            REPO_NAME: 'indra-deepika/SE_Bonus_Test_Repo'
            FILE_PATH: '/books-web/src/main/java/com/sismics/books/rest/resource/UserResource.java'
          run: python pullRequest.py design_smells_output.txt


