name: Run DesigniteJava Analysis

on: [push, pull_request]

jobs:
  designite_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Ensures the whole repository is checked out

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run DesigniteJava
      run: java -jar ./DesigniteJava.jar -i ../SE_Bonus_Test_Repo -o ./DesginiteJavaOutput

    # Optional: Upload DesigniteJava results as an artifact
    - uses: actions/upload-artifact@v2
      with:
        name: designite-results
        path: designite_output/
