name: Run DesigniteJava Analysis on External Repository

on: [push, pull_request]

jobs:
  designite_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout external repository
      uses: actions/checkout@v2
      with:
        repository: 'indra-deepika/SE_Bonus_Test_Repo'
        fetch-depth: 0 # Ensures the whole repository is checked out

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # # Assuming DesigniteJava.jar needs to be downloaded or is not in the external repository
    # - name: Download DesigniteJava.jar
    #   run: wget -O DesigniteJava.jar https://example.com/path/to/DesigniteJava.jar

    - name: Run DesigniteJava
      run: java -jar DesigniteJava.jar -i . -o ./DesigniteJavaOutput

    # Optional: Upload DesigniteJava results as an artifact
    - uses: actions/upload-artifact@v2
      with:
        name: designite-results
        path: ./DesigniteJavaOutput/

